# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-25 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicSchool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='Startd',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
