# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-25 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicSchool', '0002_study_startd'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='Stopd',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
