# Generated by Django 2.1.7 on 2019-04-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicSchool', '0003_study_stopd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Snname',
            new_name='Snickname',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='Learnday',
            new_name='Learn_day',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='Learnhour',
            new_name='Learn_hour',
        ),
        migrations.RenameField(
            model_name='teach',
            old_name='Teachday',
            new_name='Teach_day',
        ),
        migrations.RenameField(
            model_name='teach',
            old_name='Teachhour',
            new_name='Teach_hour',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Tnname',
            new_name='Tnickname',
        ),
    ]
