# Generated by Django 2.1.dev20180203235110 on 2019-04-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicSchool', '0005_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Temail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Ttel',
            field=models.IntegerField(default=0),
        ),
    ]
