# Generated by Django 2.1.dev20180203235110 on 2019-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicSchool', '0006_auto_20190409_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Ttel',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
