# Generated by Django 2.2 on 2019-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicSchool', '0008_auto_20190409_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='Startd',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='study',
            name='Stopd',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['student'], name='MusicSchool_student_6b09de_idx'),
        ),
        migrations.AddIndex(
            model_name='teach',
            index=models.Index(fields=['teacher'], name='MusicSchool_teacher_48103e_idx'),
        ),
    ]
